subscription OrderCreated {
  event {
    ... on OrderCreated {
      order {
        id
        number
        created
        status
        paymentStatus
        shippingAddress {
          firstName
          lastName
          streetAddress1
          streetAddress2
          city
          countryArea
          postalCode
          phone
          country {
            country
            code
          }
        }
        total {
          gross {
            amount
            currency
          }
        }
        lines {
          productName
          quantity
          variant {
            sku
            weight {
              value
              unit
            }
          }
        }
      }
    }
  }
}